### ISSUE TITLE
假如是子View的高是父View成比例关系，还可以用吗？

### ISSUE THREAD

**Issue by z-wade** [forkingdog/UIView-FDCollapsibleConstraints#1]
如题目一样，当子View与父View的宽成比例关系，还能实现例子的效果不？谢谢~

**Comment by MichaelPei** [comment]
应该用不了。
Auto Layout 的计算公式是：

```
 firstItem.firstAttribute {==,<=,>=} secondItem.secondAttribute * multiplier + constant
```

现在的实现是通过修改 NSLayoutConstraint 的 constant 属性来实现的，multiplier 属性没有修改。
你所说的比例关系是通过 multiplier属性实现的，要实现你说的，需要修改 multiplier 属性，但是multiplier 属性是只读的。

**Comment by sunnyxx** [comment]
@MichaelPei 说的没错，实现时只能修改`constant = 0` 来让这条约束不参与计算，`multiplier`不让修改是特别蛋疼的设计。

**Comment by z-wade** [comment]
嗯，我也是发现multiplier是只读属性。

**Comment by sunnyxx** [comment]
下一版可以尝试下使用删除constraint而不是`constant = 0`的方式废除一个约束，可能能解决这个问题。
