### ISSUE TITLE
iOS 10.2 beta 上出现循环调用，10.2以下版本正常

### ISSUE THREAD

**Issue by sweetday** [forkingdog/UIView-FDCollapsibleConstraints#16]
![6899cb3e-c083-48e9-b671-7b6e9075700c](https://cloud.githubusercontent.com/assets/15280442/21101695/4ae22c16-c0b5-11e6-93f7-08ca814471f3.png)

**Comment by faimin** [comment]
这个问题跟 [#263](https://github.com/forkingdog/UITableView-FDTemplateLayoutCell/issues/263) 应该是一个问题，可以参考一下

**Comment by afantree** [comment]
的确，一样的问题
