### ISSUE TITLE
NSLayoutConstraint Aspect Ratio

### ISSUE THREAD

**Issue by paoloandrea** [forkingdog/UIView-FDCollapsibleConstraints#2]
Hi,
there's a way to use the Aspect Ratio constraints?
I need use a dynamical height.
Thank's to respond me.

**Comment by MichaelPei** [comment]
Should be NO.
Aspect Ratio rely on multiplier property of NSLayoutConstraint, which is readonly.

**Comment by sunnyxx** [comment]
NO for now, just support make a constraint inactive by setting its `constant` to 0, but it can be done maybe next version.
