### ISSUE TITLE
使用时要注意提前注册自定义cell

### ISSUE THREAD

**Issue by wonderffee** [forkingdog/UIView-FDCollapsibleConstraints#4]
如果自定义cell是在xib中，使用时要注意提前注册自定义cell：
for (NSString *identifier in @[@"MyTableViewCell"])
[self.tableView registerNib:[UINib nibWithNibName:identifier bundle:nil]
forCellReuseIdentifier:identifier];

而不能在cellForRowAtIndexPath方法中加载nib，要不然会崩溃，比如下面的形式：
if (cell == nil)
{
NSArray *nibArray = [[NSBundle mainBundle] loadNibNamed:@"MyTableViewCell" owner:self options:nil];
cell = (GoodDetailNormalTextTableViewCell *)[nibArray objectAtIndex:0];
}

**Comment by qpwang** [comment]
update 一下，提前更具体的是指给tableView设置delegate之前，即`self.tableView.delegate = self;`之前
