### ISSUE TITLE
iOS 8.4 环境下，在 tableView 新增 tableViewCell 时 fd_collapsed = YES 第一次不生效。

### ISSUE THREAD

**Issue by qpwang** [forkingdog/UIView-FDCollapsibleConstraints#8]
![demo](https://cloud.githubusercontent.com/assets/1998065/9380304/e84cdc40-4761-11e5-9793-ca663dfeb603.gif)
cell 在第一次显示时，自动约束没有生效，刷一下就好了。

Demo 地址： https://github.com/qpwang/UIView-FDCollapsibleConstraints/tree/bugDemo

给大图的 width 和右边距 设了 fd 约束。 每次点击按钮，增加 tableView 行数、刷新 tableView。
![screen shot 2015-08-20 at 5 37 56 pm](https://cloud.githubusercontent.com/assets/1998065/9380404/85a4b9fe-4762-11e5-98a3-fc6551a70af5.png)
![screen shot 2015-08-20 at 5 38 05 pm](https://cloud.githubusercontent.com/assets/1998065/9380407/8a59b918-4762-11e5-99ca-86f65c83d038.png)

**Comment by qpwang** [comment]
![screen shot 2015-08-20 at 5 48 32 pm](https://cloud.githubusercontent.com/assets/1998065/9380577/b3e7b23e-4763-11e5-9e6e-8dae2c4ba5e9.png)
把 fd_collapsed 的逻辑放到 `- (void)updateConstraints` 就不会有这个问题。

**Comment by sunnyxx** [comment]
这里的 Auto Collapse 被你打开了，关了就好了  
![image](https://cloud.githubusercontent.com/assets/2410234/9399728/a4b2257e-47ea-11e5-957f-65a0b4a3ba45.png)

PS：这个属性在 iOS7 上有 bug，还是用手动 collapse 的方式来压缩约束吧

**Comment by qpwang** [comment]
确实是这样，多谢。
希望 readme 里面也可以说明一下。
